version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - oauth.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=shop_manager
      - POSTGRES_PASSWORD=MotDePasseCompliqueEtTropLong
      - POSTGRES_DB=shops_management
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=shop_manager
      - POSTGRES_PASSWORD=MotDePasseCompliqueEtTropLong
      - POSTGRES_DB=shops_management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
